@startuml

hide methods
hide stereotypes
skinparam linetype ortho
skinparam classAttributeIconSize 0
left to right direction

entity "Тип здания" as building_type {
    __Идентификатор типа__
    Наименование
}

entity "Здание" as building {
    __Идентификатор здания__
    Наименование
}

entity "Материал" as material {
    __Идентификатор материала__
    Наименование
    Единица измерения
}

entity "Специальность" as specialty {
    __Идентификатор специальности__
    Наименование
}

entity "Рабочий" as worker {
    __Идентификатор рабочего__
    ФИО
    Табельный номер
}

entity "Бригада" as brigade {
    __Идентификатор бригады__
    Этап работ
    Дата начала
    Дата окончания
}

building_type ||--o{ building : относится
building }o--o{ material : использует
worker }o--o{ specialty : имеет
building ||--o{ brigade : объект
specialty ||--o{ brigade : профиль
worker ||--o{ brigade : бригадир
worker }o--o{ brigade : входит в состав

@enduml