@startuml

hide methods
hide stereotypes
skinparam linetype ortho
skinparam classAttributeIconSize 0
left to right direction

entity "Тип здания" as building_type {
    Идентификатор типа
    Наименование
}

entity "Здание" as building {
    Идентификатор здания
    Наименование
}

entity "Материал" as material {
    Идентификатор материала
    Наименование
    Единица измерения
}

entity "Материалы здания" as building_material {
    Требуемое количество
}

entity "Специальность" as specialty {
    Идентификатор специальности
    Наименование
}

entity "Рабочий" as worker {
    Идентификатор рабочего
    ФИО
    Табельный номер
}

entity "Специальности рабочего" as worker_specialty

entity "Бригада" as brigade {
    Идентификатор бригады
    Этап работ
    Дата начала
    Дата окончания
}

entity "Состав бригады" as brigade_member

building_type ||--o{ building : относится

building ||--o{ building_material : требует
material ||--o{ building_material : используется

worker ||--o{ worker_specialty : имеет
specialty ||--o{ worker_specialty : соответствует

building ||--o{ brigade : объект
specialty ||--o{ brigade : профиль
worker ||--o{ brigade : бригадир

brigade ||--o{ brigade_member : состав
worker ||--o{ brigade_member : назначен

@enduml